inputs = open("./input.txt","r")
output = open("./output.txt","w")
Lines = inputs.readlines()
print("input.txt:\n{0}".format(Lines))
output.write("Copy from ./input.txt\n")
output.writelines(Lines)
print(open('input.txt').read())
for line in open('./input.txt'):
    print(line, end='')
inputs.close()
output.close()
