a = 3
b = 4
print('a = ',a)
print('b = ',b)
print('(a + 1 , a – 1) = ' , ( a + 1 , a - 1 ) )
print('( b * 3 , b / 2 ) = ' , (  b * 3 , b / 2 ) )
print('( a % 2 , b ** 2 ) = ' , ( a % 2 , b ** 2 ) )
print('( 2 + 4.0 , 2.0 ** b ) = ' , ( 2 + 4.0 , 2.0 ** b ) )
print('( b / ( 2.0 + a ) ) = ' , b / ( 2.0 + a ) )
print('( b / 2 + a ) = ' ,  b / 2 + a )
