x = set('abcde')
y = set('bdxyz')
print("x = ",x)
print("'e' in x = ", 'e' in x)
print("x - y = ",x - y)
print("x | y = ",x | y)
print("x & y = ",x & y)
print("x ^ y = ",x ^ y)
print("x > y = ",x > y)
print("x < y = ",x < y)
z = x.intersection(y)
print('z = ', z )
z.add('SPAM')
print('z = ', z )
z.update(set(['X' , 'Y']))
print('z = ', z )
z.remove('b')
print('z = ', z )
for item in set('abc'):
    print(item * 3)
S = set([ 1 , 2 , 3 ])
S = S | set([ 3 , 4 ])
print(S)
print(S.intersection((1, 3, 5)))
