x = set('abcde')
y = set('bdxyz')
print("x = ",x)
print("'e' in x = ", 'e' in x)
print("x - y = ",x - y)
print("x | y = ",x | y)
print("x & y = ",x & y)
print("x ^ y = ",x ^ y)
print("x > y = ",x > y)
print("x < y = ",x < y)
z = x.intersection(y)
print('z = ', z )
z.add('SPAM')
print('z = ', z )
z.update(set(['X' , 'Y']))
print('z = ', z )
